project:
  type: website
  output-dir: ./docs
  
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
    theme: lumen
    highlight: tango
    df_print: paged
    lib_dir: site_libs
    self_contained: no
    
# All icons were obtained from https://icons.getbootstrap.com/
website:   
  page-navigation: true
  title: "NECOMMIT Fall '23"
  navbar:
 
    left:
    - text: cheat sheet
      href: /activity/2021_cheat_sheet.qmd
    - icon: NYC 
      href: https://www.nyc.gov/site/nypd/stats/reports-analysis/stopfrisk.page
    - text: R
      href: https://posit.cloud/


      
    
    right:
    - icon: github
      href: https://github.com/Nics-Github/NECOMMIT-2023

    - text: Sources
      href: /sources/websites.qmd
    - text: Schwab
      href: schwab.qmd
  
  page-footer:
    right: 
    - text: credits
      href: credits.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



