---
title: "Stop Question Frisk EDA"
author: "Schwab"
format: html
editor: visual
---

## Load Data

```{r load}
library(tidyverse)
library(readr)
library(readxl)
sqf_2003 <- read_csv("data/2003.csv")

sqf_2015 <- read_csv("data/sqf-2015.csv")

sqf_2022 <- read_excel("data/sqf-2022.xlsx")

sqf_2019 <- read_excel("data/sqf-2019.xlsx")

```

# 2022 EDA

```{r view}

glimpse(sqf_2022)

```

```{r bar_graph_race}
sqf_2022 |>
  ggplot(aes(STOP_LOCATION_BORO_NAME, fill=SUSPECT_RACE_DESCRIPTION )) +
  facet_grid(~SUSPECT_ARRESTED_FLAG
  )+
  geom_bar(position = "fill")+
  coord_flip()

```

```{r white-black-arrests}
sqf_2022 |>
  filter(SUSPECT_RACE_DESCRIPTION %in% c("BLACK","WHITE")) |>
  ggplot(aes(STOP_LOCATION_BORO_NAME, fill=SUSPECT_RACE_DESCRIPTION )) +
  facet_grid(~SUSPECT_ARRESTED_FLAG
  )+
  geom_bar(position = "fill")+
  coord_flip()

```

```{r asked-for-constent}
sqf_2022 |>
  filter(SUSPECT_RACE_DESCRIPTION %in% c("BLACK","WHITE")) |>
  ggplot(aes(x=ASK_FOR_CONSENT_FLG, fill=SUSPECT_RACE_DESCRIPTION )) +
  facet_grid(~FRISKED_FLAG)+
  geom_bar()+
  coord_flip()
```

```{r}

```

# 2003 EDA

```{r recode-race}

 
# We are renaming the column control_text from control
sqf_2003$race_text <-
  recode(
    sqf_2003$race, 
    "A" =	"API",
    "B"	= "BLACK",
    "I"=	"AMERICAN INDIAN/ALASKAN NATIVE",
    "P"=	"HISPANIC",
    "Q"=	"HISPANIC",
    "W"=	"WHITE",
    "X"=	"UNKNOWN",
    "Z"=	"OTHER",
    .default = NA_character_
  )


```

```{r combine-hispanic}
sqf_2023_combine <- sqf_2003 |>
  mutate(race_text = )
```

```{r}
sqf_2003 |>
  ggplot(mapping=aes(x=race_text))+
  geom_bar()+
  coord_flip()
```

```{r}
sqf_2003 |> 
  select(race_text,frisked,searched,city,arstmade)|>
  count(race_text,frisked, arstmade,sort=TRUE)|>
  filter(race_text %in% c("BLACK","WHITE"))|>
  filter(race_text )
  summarise(race_text,prop = n/sum(n))

# fct_recode(sqf_2003$race_text, Hispanic = "W-HISPANIC", Hispanic = "B-HISPANIC")

```
